server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 7007
  connection-timeout: 5000ms

spring:
  application:
    name: block-dubbo-provider
# Dubbo 配置文件
dubbo:
  application:
    name: block-dubbo-provider
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    client: curator
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.boot.provider
#  #多注册中心。这里指定了registry2为默认注册中心
#  registries:
#    registry1:
#      address: zookeeper://127.0.0.1:2181
#    registry2:
#      address: zookeeper://127.0.0.1:2182
#      default: true

  #  单个注册中心
  #  registry:
  #    address: zookeeper://127.0.0.1:2181