server:
  tomcat:
    uri-encoding: UTF-8
  port: 7016
spring:
  profiles:
    active: dev
  application:
    name: zoo-keeper
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
