# server
server:
  port: 8081

  servlet:
    session:
      timeout: 60 # spring setting
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-security-chapter-two?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true


deepxi:
  iam:
    login:
      log:
        url: "http://localhost:9302/deepexi-staff-iam-openapi/api/v1.0/operatelog"

