# server
server:
  port: 8080
# spring setting
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-security-chapter-two?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456